[platformio]
default_envs = nucleo_f446re

[env]
platform = ststm32
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.0.4

[env:nucleo_f446re]
board = nucleo_f446re
build_flags =
  -D AXIOM_MCU_STM32_F446RE

[env:nucleo_f103rb]
board = nucleo_f103rb
build_flags =
  -D AXIOM_MCU_STM32_F103RB

[env:nucleo_h743zi]
board = nucleo_h743zi
build_flags =
  -D AXIOM_MCU_STM32_H7
